### ISSUE TITLE
Task Filters 

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#182]
Enhance the filtering functionality of the platform to improve user experience and data accessibility.

**Tasks:**

1. **Update URL with Applied Filters:**
   - [ ] Ensure the URL dynamically updates to reflect the filters applied by the user for easy sharing and bookmarking.

2. **Improve Filters:**
     - [ ] Make filters dynamic based on present metadata.
     - [ ] Remove this previous three from hardcoded subItems
   - **Has Reward:**
     - [ ] Create a filter to display items that offer rewards.
     - [ ] Implement a reward amount slider to allow users to specify the range of reward amounts when the "Has Reward" filter is active.

**Comment by Guboehm** [comment]
@nomadbitcoin pr is open #219

**Comment by Guboehm** [comment]
@nomadbitcoin close this issue please
